# Generated by Django 3.1.4 on 2020-12-25 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('numberOfVerses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resouceName', models.CharField(max_length=200)),
                ('numberOfChapters', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanskritContent', models.CharField(max_length=500)),
                ('translations', models.CharField(max_length=500)),
                ('chapterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanskrit.chapters')),
                ('resouceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanskrit.resources')),
            ],
        ),
        migrations.AddField(
            model_name='chapters',
            name='resourceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanskrit.resources'),
        ),
    ]
