# Generated by Django 3.1.4 on 2021-01-10 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanskrit', '0003_auto_20210103_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='resouceId',
            new_name='resourceId',
        ),
    ]
